title: "Edith Mahano's Portfolio"
logo: img/nny.jpg
description: "Mechanical Engineering Portfolio: DIY Projects, Arduino Programming, and Autonomous Systems"
show_downloads: true
theme: jekyll-theme-minimal
lang: eng
